// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: diagnostics_api.proto

package base

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DiagnosticsServiceClient is the client API for DiagnosticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DiagnosticsServiceClient interface {
	/// Send diagnostics request
	SendDiagnosticsQuery(ctx context.Context, in *DiagnosticsRequest, opts ...grpc.CallOption) (*DiagnosticsResponse, error)
}

type diagnosticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDiagnosticsServiceClient(cc grpc.ClientConnInterface) DiagnosticsServiceClient {
	return &diagnosticsServiceClient{cc}
}

func (c *diagnosticsServiceClient) SendDiagnosticsQuery(ctx context.Context, in *DiagnosticsRequest, opts ...grpc.CallOption) (*DiagnosticsResponse, error) {
	out := new(DiagnosticsResponse)
	err := c.cc.Invoke(ctx, "/base.DiagnosticsService/SendDiagnosticsQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiagnosticsServiceServer is the server API for DiagnosticsService service.
// All implementations must embed UnimplementedDiagnosticsServiceServer
// for forward compatibility
type DiagnosticsServiceServer interface {
	/// Send diagnostics request
	SendDiagnosticsQuery(context.Context, *DiagnosticsRequest) (*DiagnosticsResponse, error)
	mustEmbedUnimplementedDiagnosticsServiceServer()
}

// UnimplementedDiagnosticsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDiagnosticsServiceServer struct {
}

func (UnimplementedDiagnosticsServiceServer) SendDiagnosticsQuery(context.Context, *DiagnosticsRequest) (*DiagnosticsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendDiagnosticsQuery not implemented")
}
func (UnimplementedDiagnosticsServiceServer) mustEmbedUnimplementedDiagnosticsServiceServer() {}

// UnsafeDiagnosticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiagnosticsServiceServer will
// result in compilation errors.
type UnsafeDiagnosticsServiceServer interface {
	mustEmbedUnimplementedDiagnosticsServiceServer()
}

func RegisterDiagnosticsServiceServer(s grpc.ServiceRegistrar, srv DiagnosticsServiceServer) {
	s.RegisterService(&DiagnosticsService_ServiceDesc, srv)
}

func _DiagnosticsService_SendDiagnosticsQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiagnosticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosticsServiceServer).SendDiagnosticsQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/base.DiagnosticsService/SendDiagnosticsQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosticsServiceServer).SendDiagnosticsQuery(ctx, req.(*DiagnosticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DiagnosticsService_ServiceDesc is the grpc.ServiceDesc for DiagnosticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiagnosticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "base.DiagnosticsService",
	HandlerType: (*DiagnosticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendDiagnosticsQuery",
			Handler:    _DiagnosticsService_SendDiagnosticsQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "diagnostics_api.proto",
}
